Repository AnalogStudiosRI/www.blissfestri.com, pull requests merged in 2023-04, with the labels that each got.

#26 Feature/issue 7 event details component
  src/assets/images/analog-studios-logo.webp
  src/assets/images/iyrs-logo.webp
  src/assets/images/ri-map.webp
  src/components/event-details/event-details.js
  src/components/event-details/event-details.spec.js
  src/components/event-details/event-details.stories.js
Labels: help wanted, feature

#29 set signup form `<input>` text color to dark to improve contrast and legibility
  src/components/signup-form/signup-form.js
Labels: bug

#32 Feature/issue 8 mobile treatment and responsiveness
  src/components/event-details/event-details.js
  src/components/header/header.js
  src/components/signup-form/signup-form.js
  tailwind.config.cjs
Labels: feature

#36 landing page components integration and content
  src/components/event-details/event-details.js
  src/components/signup-form/signup-form.js
  src/pages/index.html
Labels: feature

#38 Added the Facebook link of blissfest
  src/components/signup-form/signup-form.js
Labels: feature

#40 adopt mobile version of RI map image
  src/assets/images/ri-map-mobile.webp
  src/components/event-details/event-details.js
Labels: bug

#37 add meta and open graph tags
  src/assets/images/blissfest-icon-og.png
  src/pages/index.html
Labels: feature

#41 apply lighthouse recommendations
  src/assets/images/blissfest-logo-lg.webp
  src/assets/images/blissfest-logo-md.webp
  src/assets/images/blissfest-logo-sm.webp
  src/assets/images/ri-map-mobile.webp
  src/components/event-details/event-details.js
  src/components/header/header.js
  src/components/signup-form/signup-form.js
  src/pages/index.html
  src/styles/theme.css
  tailwind.config.cjs
Labels: enhancement

#42 refine metadata tags and add favicon
  src/favicon.ico
  src/pages/index.html
Labels: feature
