Repository AnalogStudiosRI/www.blissfestri.com, pull requests merged in 2023-05, with the labels that each got.

#45 upgrade latest greenwood 0.28.0
  package-lock.json
  package.json
Labels: chore

#66 Chore/upgrade tailwind v3
  package-lock.json
  package.json
  tailwind.config.js
Labels: chore

#64 #61 header bg refactored
  src/components/header/header.js
Labels: enhancement

#68 navigation component
  src/components/navigation/navigation.js
  src/components/navigation/navigation.spec.js
  src/components/navigation/navigation.stories.js
Labels: feature

#62 create shared app template for pages
  src/pages/index.html
  src/templates/app.html
Labels: chore

#69 correctly structure `<bf-header>` and `<main>` tags in the app template
  src/pages/index.html
  src/templates/app.html
Labels: bug

#72 rename signup form component to newsletter signup
  src/components/newsletter-signup/newsletter-signup.js
  src/components/newsletter-signup/newsletter-signup.spec.js
  src/components/newsletter-signup/newsletter-signup.stories.js
  src/components/signup-form/signup-form.stories.js
  src/pages/index.html
  src/styles/main.css
Labels: feature, first wave

#73 feature/issue 51 Tickets page
  src/assets/images/ga-ticket.webp
  src/assets/images/get-tickets.webp
  src/assets/images/vip-ticket.webp
  src/pages/tickets.html
  src/stories/Tech_Stack.stories.mdx
Labels: documentation, feature, integration

#71 feature/issue 57 FAQ page
  src/assets/images/iyrs-campus-ariel.webp
  src/components/faq-card/faq-card.js
  src/components/faq-card/faq-card.spec.js
  src/components/faq-card/faq-card.stories.js
  src/pages/faq.html
Labels: question, feature, content

#80 feature/issue 47 lineup component
  src/assets/images/star.webp
  src/components/lineup/lineup.js
  src/components/lineup/lineup.spec.js
  src/components/lineup/lineup.stories.js
Labels: documentation, feature

#79 feature/issue 58 Contact page
  src/assets/images/contact.webp
  src/pages/contact.html
  src/stories/Tech_Stack.stories.mdx
Labels: documentation, feature, integration

#83 Feature/issue 50 ticket info component
  src/components/newsletter-signup/newsletter-signup.js
  src/components/ticket-info/ticket-info.js
  src/components/ticket-info/ticket-info.spec.js
  src/components/ticket-info/ticket-info.stories.js
  src/styles/main.css
Labels: documentation, feature

#81 feature/issue 70 assemble first wave of pages and content
  src/assets/images/blissfest-icon-og-v2.png
  src/assets/images/blissfest-icon-og.png
  src/assets/images/blissfest-logo-lg.webp
  src/assets/images/blissfest-logo-md.webp
  src/assets/images/blissfest-logo-xl.webp
  src/assets/images/ri-map.webp
  src/assets/images/screen-form-edge.png
  src/assets/images/screen-form-edge.webp
  src/components/header/header.js
  src/components/lineup/lineup.js
  src/components/navigation/navigation.js
  src/components/navigation/navigation.spec.js
  src/components/ticket-info/ticket-info.js
  src/pages/contact.html
  src/pages/faq.html
  src/pages/index.html
  src/pages/tickets.html
  src/styles/main.css
  src/templates/app.html
Labels: feature, content

#85 bug/use root relative paths for font files
  src/styles/theme.css
Labels: bug

#84 feature/issue 59 News page and kickoff newsletter post
  src/assets/images/blissfest-icon-sm.webp
  src/components/navigation/navigation.js
  src/components/navigation/navigation.spec.js
  src/pages/news/2023/welcome-to-blissfest.md
  src/pages/news/index.md
  src/styles/news.css
  src/templates/news.html
Labels: feature, content
