Repository AnalogStudiosRI/www.blissfestri.com, pull requests merged in 2023-06, with the labels that each got.

#86 upgrade greenwood v0.28.4
  package-lock.json
  package.json
Labels: chore

#88 Enhancement/issue 87 improve CLS for navigation text sizing
  src/components/navigation/navigation.js
Labels: enhancement

#91 Feature/issue 49 footer component
  src/assets/images/tear-strip-upside-down.webp
  src/components/footer/footer.js
  src/components/footer/footer.spec.js
  src/components/footer/footer.stories.js
  src/components/newsletter-signup/newsletter-signup.js
  src/components/newsletter-signup/newsletter-signup.spec.js
  src/pages/tickets.html
  src/templates/app.html
Labels: documentation, feature

#96 content/clarify refund policy for tickets
  src/pages/faq.html
Labels: content

#95 clean up extraneous markup
  src/pages/tickets.html
  src/templates/app.html
Labels: enhancement

#100 chore/rename lineup component to lineup poster
  src/components/lineup-poster/lineup-poster.js
  src/components/lineup-poster/lineup-poster.spec.js
  src/components/lineup-poster/lineup-poster.stories.js
  src/components/lineup/lineup.stories.js
  src/pages/index.html
Labels: chore

#103 fix: issue 99 home page layout overflow on mobile devices
  src/components/lineup-poster/lineup-poster.js
Labels: bug

#97 feature/issue 92 privacy policy and terms of use pages
  src/components/footer/footer.js
  src/components/footer/footer.spec.js
  src/pages/privacy-policy.html
  src/pages/terms-of-use.html
Labels: feature, content

#101 feature/issue 48 lineup card component
  src/assets/images/apple-icon.png
  src/assets/images/spotify-icon.png
  src/assets/images/website-icon.png
  src/components/lineup-card/lineup-card.js
  src/components/lineup-card/lineup-card.spec.js
  src/components/lineup-card/lineup-card.stories.js
  src/components/lineup-card/mock-artist.js
Labels: documentation, feature

#102 add ESLint formatting rules for whitespace and ending line breaks
  .eslintrc.cjs
  src/components/event-details/event-details.spec.js
  src/components/faq-card/faq-card.spec.js
  src/components/faq-card/faq-card.stories.js
  src/components/header/header.spec.js
  src/components/header/header.stories.js
  src/components/lineup-card/lineup-card.spec.js
  src/components/lineup-poster/lineup-poster.spec.js
  src/components/navigation/navigation.stories.js
  src/components/newsletter-signup/newsletter-signup.spec.js
  src/components/newsletter-signup/newsletter-signup.stories.js
  web-test-runner.config.js
Labels: chore

#98 enhancement/issue 93 reuse header background image for footer
  src/assets/images/tear-strip-upside-down.webp
  src/components/footer/footer.js
Labels: enhancement

#108 Feature/issue 54 lineup page
  netlify.toml
  src/assets/images/lineup/allysen-callery.webp
  src/assets/images/lineup/analog.webp
  src/assets/images/lineup/bill-bartholomew.webp
  src/assets/images/lineup/jabbawaukee.webp
  src/assets/images/lineup/jesse-the-tree.webp
  src/assets/images/lineup/nate-farrar.webp
  src/assets/images/lineup/the-z-boys.webp
  src/components/lineup-card/lineup-card.js
  src/components/lineup-card/lineup-card.spec.js
  src/components/lineup-card/lineup-card.stories.js
  src/components/lineup-card/mock-artist.js
  src/components/lineup-poster/lineup-poster.js
  src/components/lineup-poster/lineup-poster.spec.js
  src/components/navigation/navigation.js
  src/components/navigation/navigation.spec.js
  src/pages/lineup.js
  src/services/lineup-service.js
Labels: feature, content

#110 content/lineup announcement news post
  src/pages/news/2023/full-lineup-reveal.md
  src/pages/news/index.md
  src/styles/news.css
Labels: content

#114 fix blissfest facebook footer link labels
  src/components/footer/footer.js
  src/components/footer/footer.spec.js
Labels: bug, content

#113 enhancement/update blissfest instagram footer link
  src/components/footer/footer.js
  src/components/footer/footer.spec.js
Labels: enhancement, content

#112 high quality background image for lineup poster
  src/assets/images/iyrs/iyrs-facade.webp
  src/components/lineup-poster/lineup-poster.js
Labels: enhancement

#116 moved remaining iyrs photos to iyrs folder
  src/assets/images/iyrs/iyrs-campus-ariel.webp
  src/pages/faq.html
Labels: chore

#117 refactor lineup poster to use lineup service for lineup content
  src/components/lineup-poster/lineup-poster.js
  src/services/lineup-service.js
Labels: enhancement

#118 Feature/add promo video to home page
  src/components/promo-video/promo-video.js
  src/components/promo-video/promo-video.spec.js
  src/components/promo-video/promo-video.stories.js
  src/pages/index.html
Labels: feature, content

#120 enable promo video to played in fullscreen
  src/components/promo-video/promo-video.js
Labels: enhancement
