Repository AnalogStudiosRI/www.blissfestri.com, pull requests merged in 2023-03, with the labels that each got.

#12 Chore/upgrade storybook7
  .gitignore
  .ls-lint.yml
  .storybook/main.cjs
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
Labels: chore

#13 create theme and styleguide
  src/assets/fonts/citrus-gothic-rough-regular.woff2
  src/assets/fonts/montserrat-regular.ttf
  src/components/header/header.js
  src/pages/index.html
  src/stories/Documentation.stories.mdx
  src/stories/Styleguide.stories.mdx
  src/styles/main.css
  src/styles/theme.css
  tailwind.config.cjs
Labels: feature

#20 fix the hex value for accent theme color in tailwind config
  tailwind.config.cjs
Labels: bug

#21 fix `font-family` CSS variable and clean up main.css
  src/pages/index.html
  src/styles/main.css
Labels: bug

#22 update theme color guidelines for WCAG AA compliance
  src/stories/Styleguide.stories.mdx
  src/styles/theme.css
  tailwind.config.cjs
Labels: bug, documentation

#24 adopt preferred convention of kebabcase for ls-lint
  .ls-lint.yml
Labels: chore

#19 signup form component
  src/assets/images/facebook-icon.png
  src/assets/images/instagram-icon.png
  src/assets/images/message-bottle.png
  src/assets/images/screen-form-edge.png
  src/assets/images/youtube-icon.png
  src/components/signup-form/signup-form.js
  src/components/signup-form/signup-form.spec.js
  src/components/signup-form/signup-form.stories.js
  src/styles/main.css
Labels: feature, bounty:claimed

#25 Feature/issue 5 header component
  src/assets/images/blissfest-logo.webp
  src/assets/images/tear-strip.webp
  src/components/header/header.js
  src/components/header/header.spec.js
Labels: feature

#28 add .editorconfig file
  .editorconfig
Labels: chore
